kind: Service
apiVersion: v1
metadata:
    name: transmission-service
    namespace: transmission
spec:
    type: LoadBalancer
    loadBalancerIP: 172.16.23.27
    selector:
        app: transmission
    ports:
    - protocol: TCP
      name: web-interface
      port: 80
    - protocol: TCP
      name: torrent-tcp
      port: 51413
    - protocol: UDP
      name: torrents-udp
      port: 51413